### ISSUE TITLE
В ховере и в сигнатурах нет информации о передаче по значению (знач)

### ISSUE THREAD

**Issue by pumbaEO** [xDrivenDevelopment/onec-syntaxparser#3]
xDrivenDevelopment/1c-syntax#169

**Comment by pumbaEO** [comment]
@nixel2007  как ты себе это представляешь? Сейчас у нас существует массив Params и туда просто передаетса Параметр имя, с регуляркой на фильтр Знач|Val, по факту должно быть тогда передача не строки, а объекта типа {"name": "МойПараметр", "byVal":true} ?

**Comment by nixel2007** [comment]
@pumbaEO да, похоже на то
